### ISSUE TITLE
Template for IAM policies

### ISSUE THREAD

**Issue by EmFl** [EverythingMe/rainbow#28]
Hello,
I'm trying to use rainbow to create an iam policy and was thinking having something like this as template : 

``` yaml
Parameters:
 PolicyName: {Type: String}
 PolicyGroups: {Type: CommaDelimitedList}
Resources:
 mypolicy:
  Type: AWS::IAM::Policy
  Properties:
   PolicyName: {Ref: PolicyName}
   PolicyDocument: {!file files/policy.json}
   Groups: {Ref: PolicyGroups}
```

With files/policy.json having the following : 

``` json
{
   "Statement":[{
      "Effect":"Allow",
      "NotAction": ["ec2:describe*"],
      "Resource":["*"],
      "Condition": {"Null": {"aws:MultiFactorAuthAge": "false"}}
      }
   ]
}
```

Or even better do a PolicyDocument in parameter and call a !file {Ref: PolicyDocument} in the resource block.

However, none of this seems to work. If i need to write the policy in yaml directly then I don't see the use of the template as I would need one per policy :\

``` yaml
Resources:
 mypolicy:
  Type: AWS::IAM::Policy
  Properties:
   PolicyName: mypolicy
   PolicyDocument:
    Statement:
    - Effect: Allow
      NotAction:
      - "ec2:describe*"
      Resource:
      - "*" 
      Condition:
       "Null": 
        "aws:MultiFactorAuthAge": false
   Groups: 
```

**Comment by omribahumi** [comment]
@EmFl sorry, missed the notification about your issue.

You can use
`PolicyDocument: !file files/policy.json`
(no need for the extra `{` `}`)

You can also have an entire file

``` yaml
Parameters:
 PolicyName: {Type: String}
 PolicyGroups: {Type: CommaDelimitedList}
Resources:
 mypolicy:
  Type: AWS::IAM::Policy
  Properties:
   PolicyName: {Ref: PolicyName}
   PolicyDocument:
     {
        "Statement":[{
           "Effect":"Allow",
           "NotAction": ["ec2:describe*"],
           "Resource":["*"],
           "Condition": {"Null": {"aws:MultiFactorAuthAge": "false"}}
           }
        ]
     }
   Groups: {Ref: PolicyGroups}
```

And merge it to another template when running `rainbow`
