### ISSUE TITLE
The ability to pass in a file to represent the parameters

### ISSUE THREAD

**Issue by sstarcher** [EverythingMe/rainbow#3]
I have several stacks to manage and to not have to create several shell scripts something along the lines of.

stack.yaml
```
logstash:
  data-sources:
    - cfn_resources:VPC
    - cfn_resources:other
    - yaml:stacks/logstash.yaml
  templates:
    - base.yaml
    - single-instance.yaml
```

execution of 
rainbow logstash --block
